### PR TITLE
fix detection of nouveau in case its builtin

### PR DESCRIPTION
**Pull request by alexxy**
Signed-off-by: Alexey Shvetsov alexxy@gentoo.org

### CODE REVIEW

**Comment by alexxy** [comment]
Also this should fix install target for gdev lib

**Comment by shinpei0208** [comment]
alexy, thanks for your commits. Will you add more commits? If not, I will merge them right away.

**Comment by shinpei0208** [comment]
What is $(DESTDIR)? Where is it defined?
- Shinpei

**Comment by alexxy** [comment]
Its defined by install phase via some kind of package manager

so it issues

make DESTDIR=$D install

**Comment by shinpei0208** [comment]
Okay, hmm, if we think about the install path, we should use ./configure script. Perhaps ../configure --prefix=XXX, and then the script should define $(PREFIX)=XXX and $(GDEVDIR)=$(PREFIX)/gdev. I would appreciate if you could further make this edit. If you are not available, I would work on it myself.

Thanks,
Shinpei

**Comment by alexxy** [comment]
Well DESTDIR is not install path. Its common feature for almoust all software install tools. Btw why not install gdev in /usr? I created gentoo packages for gdev userspace parts.
PS is there any howto about running gdev and ocelot for some king of cuda apps (may be simple ones but i preffer to run something like GROMACS 4.6)

**Comment by shinpei0208** [comment]
To the best of my knowledge, the most common feature to install Linux system tools is --prefix. I would prefer using ./configure script rather than DESTDIR. This is just my preference. I am not very familiar with DESTDIR.

If you install Gdev to /usr, it would conflict with the blob driver.

What kind of CUDA apps are you talking about? Gdev supports CUDA Driver API. If you need Runtime API, you would need Ocelot, but I haven't made any document for HOWTO. Sorry about that.

**Pull request merged**
